services: 
  frontend: 
    build: 
      context: . 
      dockerfile: Dockerfile.frontend
    container_name: flexnotes-client
    ports: 
      - "5173:80"
    volumes:  
      - /app/note_modules
    environment: 
      - NODE_ENV=development
    tty: true 
    stdin_open: true
